---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: xyz-product
spec:
  type: ClusterIP
#  type: NodePort
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
#  clusterIP: None