---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-volume-claim
  namespace: xyz-product
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi