---
apiVersion: v1
kind: Service
metadata:
  name: prod-user-reg-service
  namespace: xyz-product
spec:
  selector:
    app: prod-user-reg
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: NodePort
    