spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product?autoreconnect = true
    username: root
    password: password
  application:
    name: user-registration-service
server:
  port: 8081
  

 