---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: letsencrypt-staging-cert
  namespace: cert-manager
spec:
    secretName: letsencrypt-staging-tls
    issuerRef:
        name: letsencrypt-staging-issuer
    commonName: apps.bauxite-viu.co.uk
    acme:
        config: 
            - http01:
                ingress: haproxy
              domains:
                - apps.bauxite-viu.co.uk
---